# Change these first
owner: t-thomas-dev # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

assignees: # Users to assign downtime issues (optional)
  - t-thomas-dev

sites:
  - name: t-dev.pages.dev
    url: https://t-dev.pages.dev
    icon: https://cf-assets.www.cloudflare.com/slt3lc6tev37/CHOl0sUhrumCxOXfRotGt/081f81d52274080b2d026fdf163e3009/cloudflare-icon-color_3x.png

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Uptime monitor for sites"
  introMessage: See uptimes below
  navbar:
    - title: Status
      href: /upptime
    - title: GitHub
      href: https://github.com/t-thomas-dev/upptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
